version: '3.8'

services:
  random-ai:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    command: [ "cargo", "run", "-p", "random-ai", "--", "8081" ]
    environment:
      - HOST_ADDRESS=0.0.0.0
    ports:
      - "8081:8081"
    volumes:
      - ../:/workspace

  jroylance-ai:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    command: [ "cargo", "run", "-p", "jroylance-ai", "--", "8082" ]
    environment:
      - HOST_ADDRESS=0.0.0.0
    ports:
      - "8082:8082"
    volumes:
      - ../:/workspace

  custom-ai:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    command: [ "cargo", "run", "-p", "custom-ai", "--", "8083" ]
    environment:
      - HOST_ADDRESS=0.0.0.0
    ports:
      - "8083:8083"
    volumes:
      - ../:/workspace
    links:
      - random-ai:rai

  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /workspace
    environment:
      - FORCE_PORT=8080
      - HOST_ADDRESS=0.0.0.0
    command:
      [
        "cargo",
        "run",
        "-p",
        "game",
        "--",
        "random-ai:8081",
        "jroylance-ai:8082",
        "custom-ai:8083"
      ]
    depends_on:
      - random-ai
      - jroylance-ai
      - custom-ai
    volumes:
      - ../:/workspace
